name: recetas_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.3.1
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.11
  cached_network_image: ^3.3.1
  supabase_flutter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
